sonar.projectKey=JPEG-app_UserService
sonar.projectName=User Service
sonar.projectVersion=1.0
sonar.organization=jpeg-app

sonar.sources=src
# Ensure this path is correct. If your tests are under src/tests, this is fine.
sonar.tests=src/tests 
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

sonar.sourceEncoding=UTF-8

# Reports for analysis
sonar.javascript.linter.reportPaths=eslint-report.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml

sonar.typescript.tsconfigPath=tsconfig.json